Downloads/ICBFApp/Pages/Niños/CrearNiño.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using ICBFApp.Pages.Jardines;


namespace ICBFApp.Pages.Niños
{
    public class CrearNiñoModel : PageModel
    {
        public List<JardinInfo> jardinInfo { get; set; } = new List<JardinInfo>();
        public List<PersonaInfo> personaInfo { get; set; } = new List<PersonaInfo>();
        public NiñoInfo niñoInfo = new NiñoInfo();
        public string errorMessage = "";
        public string successMessage = "";

        public void OnGet()
        {
            try
            {
                String connectionString = "Data Source=WINDOW11-CAROLG\\SQLEXPRESS;Initial Catalog=icbf;Integrated Security=True;";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    String sqlJardin = "SELECT Identificador, Nombre FROM Jardin";
                    using (SqlCommand command = new SqlCommand(sqlJardin, connection))
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    jardinInfo.Add(new JardinInfo
                                    {
                                        Identificador = reader.GetInt32(0).ToString(),
                                        Nombre = reader.GetString(1)
                                    });
                                }
                            }
                        }
                    }

                    String sqlPersona = "SELECT Identificacion, Nombre FROM Persona";
                    using (SqlCommand command = new SqlCommand(sqlPersona, connection))
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    personaInfo.Add(new PersonaInfo
                                    {
                                        Identificacion = reader.GetInt32(0).ToString(),
                                        Nombre = reader.GetString(1)
                                    });
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                errorMessage = ex.Message;
            }
        }

        public void OnPost()
        {
            string Nombre = Request.Form["Nombre"];
            string TipoSangre = Request.Form["TipoSangre"];
            string CiudadNacimiento = Request.Form["CiudadNacimiento"];
            string Telefono = Request.Form["Telefono"];
            string Edad = Request.Form["Edad"];
            string Direccion = Request.Form["Direccion"];
            string EPS = Request.Form["EPS"];
            string Identidad = Request.Form["Identidad"];
            string Jardin = Request.Form["Jardin"];
            string Persona = Request.Form["Persona"];

            if (string.IsNullOrEmpty(Nombre) || string.IsNullOrEmpty(TipoSangre) || string.IsNullOrEmpty(CiudadNacimiento) ||
                string.IsNullOrEmpty(Telefono) || string.IsNullOrEmpty(Edad) || string.IsNullOrEmpty(Direccion) || string.IsNullOrEmpty(EPS) ||
                string.IsNullOrEmpty(Identidad) ||  string.IsNullOrEmpty(Jardin) ||
                string.IsNullOrEmpty(Persona))
            {
                errorMessage = "Todos los campos son obligatorios";
                return;
            }
            // Validación de la edad
            if (int.TryParse(Edad, out int parsedEdad))
            {
                if (parsedEdad > 6)
                {
                    errorMessage = "La edad del niño no puede superar los 6 años";
                    return;
                }
            }
            else
            {
                errorMessage = "La edad debe ser un número válido";
                return;
            }
            try
            {
                String connectionString = "Data Source=WINDOW11-CAROLG\\SQLEXPRESS;Initial Catalog=icbf;Integrated Security=True;";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    String sqlExists = "SELECT COUNT(*) FROM Niño WHERE Identidad = @Identidad";
                    using (SqlCommand commandCheck = new SqlCommand(sqlExists, connection))
                    {
                        commandCheck.Parameters.AddWithValue("@Identidad", Identidad);
                        int count = (int)commandCheck.ExecuteScalar();
                        if (count > 0)
                        {
                            errorMessage = "El niño con identificación " + Identidad + " ya existe. Verifique la información e intente de nuevo";
                            return;
                        }
                    }

                    String sqlInsert = "INSERT INTO Niño (Nombre, TipoSangre, CiudadNacimiento, Telefono, Edad, Direccion, EPS, Identidad, fkJardin, fkPersona) " +
                                       "VALUES (@Nombre, @TipoSangre, @CiudadNacimiento, @Telefono, @Edad, @Direccion, @EPS, @Identidad, @Jardin, @Persona)";

                    using (SqlCommand command = new SqlCommand(sqlInsert, connection))
                    {
                        command.Parameters.AddWithValue("@Nombre", Nombre);
                        command.Parameters.AddWithValue("@TipoSangre", TipoSangre);
                        command.Parameters.AddWithValue("@CiudadNacimiento", CiudadNacimiento);
                        command.Parameters.AddWithValue("@Telefono", Telefono);
                        command.Parameters.AddWithValue("@Edad", Edad);
                        command.Parameters.AddWithValue("@Direccion", Direccion);
                        command.Parameters.AddWithValue("@EPS", EPS);
                        command.Parameters.AddWithValue("@Identidad", Identidad);
                        command.Parameters.AddWithValue("@Jardin", Jardin);
                        command.Parameters.AddWithValue("@Persona", Persona);

                        command.ExecuteNonQuery();
                    }
                }

                successMessage = "Niño creado exitosamente";
                RedirectToPage("/Niños/Index");
            }
            catch (Exception ex)
            {
                errorMessage = ex.Message;
            }
        }
    }

}

Downloads/ICBFApp/Pages/Niños/Index.cshtml.cs
using ICBFApp.Pages.Jardines;
using ICBFApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuestPDF.Fluent;
using System.Data.SqlClient;

namespace ICBFApp.Pages.Niños
{
    public class IndexModel : PageModel
    {
        private readonly IGeneratePdfService _generatePdfService;
        private readonly IWebHostEnvironment _host;

        public IndexModel(IGeneratePdfService generatePdfService, IWebHostEnvironment host)
        {
            _generatePdfService = generatePdfService;
            _host = host;
        }
        public List<NiñoInfo> listNiño = new List<NiñoInfo>();
        public string ErrorMessage { get; set; } = "";

        public void OnGet()
        {
            try
            {
                string connectionString = "Data Source=WINDOW11-CAROLG\\SQLEXPRESS;Initial Catalog=icbf;Integrated Security=True;";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    string sqlSelect = "SELECT n.NIUP, n.Nombre, n.TipoSangre, n.CiudadNacimiento, n.Telefono, n.Edad, n.Direccion, n.EPS, n.Identidad, j.Nombre AS JardinNombre, p.Nombre AS PersonaNombre " +
                      "FROM Niño n " +
                      "JOIN Jardin j ON n.fkJardin = j.Identificador " +
                      "JOIN Persona p ON n.fkPersona = p.Identificacion";


                    using (SqlCommand command = new SqlCommand(sqlSelect, connection))
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                NiñoInfo niño = new NiñoInfo();
                                niño.NIUP = reader.GetInt32(0);
                                niño.Nombre = reader.GetString(1);
                                niño.TipoSangre = reader.GetString(2);
                                niño.CiudadNacimiento = reader.GetString(3);
                                niño.Telefono = reader.GetString(4);
                                niño.Edad = reader.GetString(5);
                                niño.Direccion = reader.GetString(6);
                                niño.EPS = reader.GetString(7);
                                niño.Identidad = reader.GetInt32(8);
                                niño.JardinNombre = reader.GetString(9);
                                niño.PersonaNombre = reader.GetString(10);

                                listNiño.Add(niño);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error: " + ex.Message;
                Console.WriteLine(ErrorMessage);
            }
        }

        public IActionResult OnPostDownloadPdf()
        {
            var report = _generatePdfService.GeneratePdfQuest();
            byte[] pdfBytes = report.GeneratePdf();
            var mimeType = "application/pdf";
            //return File(pdfBytes, mimeType, "Reporte.pdf"); // si le quito el nombre del archivo, no lo descarga auto
            return File(pdfBytes, mimeType); // si le quito el nombre del archivo, no lo descarga auto
        }
    }


    public class NiñoInfo
    {
        public int NIUP { get; set; }
        public string Nombre { get; set; }
        public string TipoSangre { get; set; }
        public string CiudadNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Edad { get; set; }
        public string Direccion { get; set; }
        public string EPS { get; set; }
        public int Identidad { get; set; } 
        public string JardinNombre { get; set; }
        public string PersonaNombre { get; set; }

        public PersonaInfo personaInfo { get; set; }
		public JardinInfo jardinInfo { get; set; }

	}
}

Downloads/ICBFApp/Pages/Personas/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using static ICBFApp.Pages.Roles.IndexModel;

namespace ICBFApp.Pages.Personas
{
    public class EditModel : PageModel
    {
        public PersonaInfo personaInfo { get; set; } = new PersonaInfo();
        public List<RolInfo> rolInfo { get; set; } = new List<RolInfo>();
        public RolInfo rolinfoSelected { get; set; } = new RolInfo();
        public string errorMessage = "";
        public string successMessage = "";

        public void OnGet()
        {
            String Identificacion = Request.Query["Identificacion"];
            try
            {
                string connectionString = "Data Source=WINDOW11-CAROLG\\SQLEXPRESS;Initial Catalog=icbf;Integrated Security=True;";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    String sqlPersona = "SELECT * FROM Persona WHERE Identificacion = @Identificacion";
                    using (SqlCommand command = new SqlCommand(sqlPersona, connection))
                    {
                        command.Parameters.AddWithValue("@Identificacion", Identificacion);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                personaInfo.Identificacion = reader.GetInt32(0);
                                personaInfo.Nombre = reader.GetString(1);
                                personaInfo.Cedula = reader.GetString(2);
                                personaInfo.Telefono = reader.GetString(3);
                                personaInfo.Direccion = reader.GetString(4);
                                personaInfo.Correo = reader.GetString(5);
                                personaInfo.Rol = reader.GetInt32(6).ToString();
                            }
                        }
                    }

                    String sqlRoles = "SELECT IdRol, Rol FROM Rol WHERE IdRol != @IdRol";
                    using (SqlCommand command = new SqlCommand(sqlRoles, connection))
                    {
                        command.Parameters.AddWithValue("@IdRol", personaInfo.Rol);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                rolInfo.Add(new RolInfo
                                {
                                    IdRol = reader.GetInt32(0).ToString(),
                                    Rol = reader.GetString(1)
                                });
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                errorMessage = ex.Message;
            }
        }

        public void OnPost()
        {
            string Identificacion = Request.Form["personaInfo.Identificacion"];
            string Nombre = Request.Form["nombre"];
            string Cedula = Request.Form["cedula"];
            string Telefono = Request.Form["telefono"];
            string Direccion = Request.Form["direccion"];
            string Correo = Request.Form["correo"];
            string fkRol = Request.Form["rol"];

            if (string.IsNullOrEmpty(Identificacion) || string.IsNullOrEmpty(Nombre) || string.IsNullOrEmpty(Cedula) || string.IsNullOrEmpty(Telefono)
                 || string.IsNullOrEmpty(Direccion)
                || string.IsNullOrEmpty(Correo) || string.IsNullOrEmpty(fkRol))
            {
                errorMessage = "Todos los campos son obligatorios";
                return;
            }

            try
            {
                string connectionString = "Data Source=WINDOW11-CAROLG\\SQLEXPRESS;Initial Catalog=icbf;Integrated Security=True;";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    String sqlUpdate = "UPDATE Persona SET " +
                                        "Nombre = @nombre, Cedula = @cedula, Telefono = @telefono, " +
                                        "Direccion = @direccion, Correo = @correo, fkRol = @fkRol WHERE Identificacion = @Identificacion";

                    using (SqlCommand command = new SqlCommand(sqlUpdate, connection))
                    {
                        command.Parameters.AddWithValue("@Identificacion", Identificacion);
                        command.Parameters.AddWithValue("@nombre", Nombre);
                        command.Parameters.AddWithValue("@cedula", Cedula);
                        command.Parameters.AddWithValue("@telefono", Telefono);
                        command.Parameters.AddWithValue("@direccion", Direccion);
                        command.Parameters.AddWithValue("@correo", Correo);
                        command.Parameters.AddWithValue("@fkRol", fkRol);

                        command.ExecuteNonQuery();
                    }
                }

                successMessage = "Persona editada exitosamente";
                RedirectToPage("/Personas/Index");
            }
            catch (Exception ex)
            {
                errorMessage = ex.Message;
            }
        }
    }
}

Downloads/ICBFApp/Pages/Niños/CrearNiño.cshtml
@page
@model ICBFApp.Pages.Niños.CrearNiñoModel
@{
}
<br>
<h2>Agregar Nuevo Niño</h2>

@if (Model.errorMessage.Length > 0)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>@Model.errorMessage</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
}

<form method="POST">
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label">Nombre</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="Nombre" value="@Model.niñoInfo.Nombre">
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="SelectedTipoSangre">Selecciona un Tipo de sangre</label>
        <div class="col-sm-6">
            <select name="TipoSangre" value="@Model.niñoInfo.TipoSangre" class="form-control">
                <option value="">Selecciona un tipo de sangre</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="0-">O-</option>
            </select>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label">CiudadNacimiento</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="CiudadNacimiento" value="@Model.niñoInfo.CiudadNacimiento">
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label">Telefono</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="Telefono" value="@Model.niñoInfo.Telefono">
        </div>
    </div>
      <div class="row mb-3">
        <label class="col-form-label-sm col-form-label">Edad</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="Edad" value="@Model.niñoInfo.Edad">
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label">Direccion</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="Direccion" value="@Model.niñoInfo.Direccion">
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="SelectedEPS">Selecciona una EPS</label>
        <div class="col-sm-6">
            <select name="EPS" value="@Model.niñoInfo.EPS" class="form-control">
                <option value="">Selecciona una Eps</option>
                <option value="NUEVA EPS">NUEVA EPS</option>
                <option value="Compensar">Compensar</option>
                <option value="Cafam">Cafam</option>
            </select>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label">Identificacion</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="Identidad" value="@Model.niñoInfo.Identidad">
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="Jardin">Seleccione un Jardín</label>
        <div class="col-sm-6">
            <select id="Jardin" name="Jardin" class="form-control">
                <option value="">Seleccione un Jardín</option>
                @foreach (var jardin in Model.jardinInfo)
                {
                    <option value="@jardin.Identificador">@jardin.Nombre</option>
                }
            </select>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="Persona">Seleccione un Acudiente</label>
        <div class="col-sm-6">
            <select id="Persona" name="Persona" class="form-control">
                <option value="">Seleccione una Persona</option>
                @foreach (var persona in Model.personaInfo)
                {
                    <option value="@persona.Identificacion">@persona.Nombre</option>
                }
            </select>
        </div>
    </div>

    @if (Model.successMessage.Length > 0)
    {
        <div class="row mb-3">
            <div class="col-sm-9">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>@Model.successMessage</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                </div>
            </div>
        </div>
    }

    <div class="row mb-3">
        <div class="offset-sm-3 col-sm-3 d-grid">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <div class="col-sm-3 d-grid">
            <a class="btn btn-outline-primary" href="/Niños/Index" role="button">Cancel</a>
        </div>
    </div>
</form>

Downloads/ICBFApp/Pages/Niños/Delete.cshtml
@page
@using System.Data.SqlClient;

@{
    try
    {
        string NIUP = Request.Query["NIUP"];
        string connectionString = "Data Source=WINDOW11-CAROLG\\SQLEXPRESS;Initial Catalog=icbf;Integrated Security=True;";
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            connection.Open();
            string sqlDelete = "DELETE FROM Niño WHERE NIUP = @NIUP";

            using (SqlCommand command = new SqlCommand(sqlDelete, connection))
            {
                command.Parameters.AddWithValue("@NIUP", NIUP);
                command.ExecuteNonQuery();
            }
        }

       
    }
    catch (Exception e)
    {
        
    }
    RedirectToPage("/Niños/Index");
}

Downloads/ICBFApp/Pages/Niños/Edit.cshtml
@page
@model ICBFApp.Pages.Niños.EditModel
@{
}
<h2>Editar Niño</h2>

@if (Model.errorMessage.Length > 0)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>@Model.errorMessage</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
}

<form method="POST">
    <input type="hidden" asp-for="niñoInfo.NIUP" />

    <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control" name="Nombre" value="@Model.niñoInfo.Nombre">
    </div>

    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="SelectedTipoSangre">Selecciona un Tipo de sangre</label>
        <div class="col-sm-6">
            <select name="TipoSangre" value="@Model.niñoInfo.TipoSangre" class="form-control">
                <option value="">Selecciona un tipo de sangre</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="0-">O-</option>
            </select>
        </div>
    </div>

    <div class="mb-3">
        <label class="form-label">Ciudad de Nacimiento</label>
        <input type="text" class="form-control" name="CiudadNacimiento" value="@Model.niñoInfo.CiudadNacimiento">
    </div>

    <div class="mb-3">
        <label class="form-label">Teléfono</label>
        <input type="text" class="form-control" name="Telefono" value="@Model.niñoInfo.Telefono">
    </div>

    <div class="mb-3">
        <label class="form-label">Edad</label>
        <input type="text" class="form-control" name="Edad" value="@Model.niñoInfo.Edad">
    </div>

    <div class="mb-3">
        <label class="form-label">Dirección</label>
        <input type="text" class="form-control" name="Direccion" value="@Model.niñoInfo.Direccion">
    </div>

    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="SelectedEPS">Selecciona una EPS</label>
        <div class="col-sm-6">
            <select name="EPS" value="@Model.niñoInfo.EPS" class="form-control">
                <option value="">Selecciona una Eps</option>
                <option value="NUEVA EPS">NUEVA EPS</option>
                <option value="Compensar">Compensar</option>
                <option value="Cafam">Cafam</option>
            </select>
        </div>
    </div>

    <div class="mb-3">
        <label class="form-label">Identificación</label>
        <input type="text" class="form-control" name="Identidad" value="@Model.niñoInfo.Identidad">
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="Jardin">Seleccione un Jardín</label>
        <div class="col-sm-6">
            <select id="Jardin" name="Jardin" class="form-control">
                <option value="">Seleccione un Jardín</option>
                @foreach (var jardin in Model.jardinInfo)
                {
                    <option value="@jardin.Identificador">@jardin.Nombre</option>
                }
            </select>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-form-label-sm col-form-label" for="Persona">Seleccione un Acudiente</label>
        <div class="col-sm-6">
            <select id="Persona" name="Persona" class="form-control">
                <option value="">Seleccione una Persona</option>
                @foreach (var persona in Model.personaInfo)
                {
                    <option value="@persona.Identificacion">@persona.Nombre</option>
                }
            </select>
        </div>
    </div>

    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a class="btn btn-secondary" href="/Niños/Index">Cancelar</a>
    </div>
</form>

Downloads/ICBFApp/Pages/Niños/Index.cshtml
@page
@model ICBFApp.Pages.Niños.IndexModel
@{
}

<h2>Lista de Niños</h2>
<a class="btn btn-primary btn-sm" href="/Niños/CrearNiño">Nuevo Niño</a>


<form method="post">
    <button type="submit" asp-page-handler="DownloadPdf">Descargar PDF</button>
</form>


@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div class="alert alert-danger">
        <strong>@Model.ErrorMessage</strong>
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>NIUP</th>
            <th>Nombre</th>
            <th>TipoSangre</th>
            <th>CiudadNacimiento</th>
            <th>Telefono</th>
            <th>Edad</th>
            <th>Direccion</th>
            <th>EPS</th>
            <th>Nombre Jardin</th>
            <th>Nombre Acudiente</th>
            <th>Identificacion</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.listNiño)
        {
            <tr>
                <td>@item.NIUP</td>
                <td>@item.Nombre</td>
                <td>@item.TipoSangre</td>
                <td>@item.CiudadNacimiento</td>
                <td>@item.Telefono</td>
                <td>@item.Edad</td>
                <td>@item.Direccion</td>
                <td>@item.EPS</td>
                <td>@item.JardinNombre</td>
                <td>@item.PersonaNombre</td>
                <td>@item.Identidad</td>
                <td>
                    <a class="btn btn-primary btn-sm" href="/Niños/Edit?NIUP=@item.NIUP">Editar</a>
                    <a class="btn btn-danger btn-sm" href="/Niños/Delete?NIUP=@item.NIUP">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>